config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get '/users/:id', to: 'user#show', as: "user"
  resources :journals, only: [:new, :create, :show, :destroy, :index]
  resources :goals
  resources :therapists, only: [:index, :show]

  get "/login", to: "users#login", as: "login"
  post "/handle_login", to: "users#handle_login"
  delete "/logout", to: "users#logout", as: "logout"

  get '/appointments/new', to: 'appointments#new', as: 'new_appointment'
  post '/appointments', to: 'appointments#create', as: 'create_appointment'
  get "/appointments", to: "appointments#index", as: "appointments"
  get "/appointments/:id", to: "appointments#show", as: "appointment"
  delete "/appointments/:id", to: "appointments#destroy"
  get '/appointments/:id/edit', to: 'appointments#edit', as: 'edit_appointment'
  patch '/appointments/:id', to: 'appointments#update'

  get '/profile', to: 'users#profile', as: 'profile'
  post '/profile', to: 'users#profile'

  get '/users/new', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'

  post '/users/new', to: "users#new"

  post '/appointments/:id/edit', to: "appointments#edit"

  post '/goals/:id/edit', to: "goals#edit"

  get '/journals/:id/edit', to: 'journals#edit', as: 'edit_journal'
  patch '/journals/:id', to: 'journals#update'
  post '/journals/:id/edit', to: 'journals#edit', as: 'e_journal'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :therapist
  belongs_to :apptime
end

app/models/apptime.rb
class Apptime < ApplicationRecord
    has_many :appointments
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user

  def status
    if self.goal_status == false
     p "In progress"
    else
      p "Completed"
    end
  end

end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user
end

app/models/therapist.rb
class Therapist < ApplicationRecord
    has_many :appointments, dependent: :destroy
    has_many :users, through: :appointments
end

app/models/user.rb
class User < ApplicationRecord
    has_many :appointments, dependent: :destroy
    has_many :therapists, through: :appointments
    has_many :journals, dependent: :destroy
    has_many :goals, -> {order ("goal_status DESC")}, dependent: :destroy

    validates :username, presence: true, uniqueness: true
    validates :password, presence: true

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :check_and_see_if_someone_is_logged_in?
    before_action :authorized_to_see_page

    def set_current_user
        # INSTANCE VARIABLES IN A BEFORE ACTION IS AVAILABLE
        @current_user = User.find_by(id: session[:user_id])
    end

    def check_and_see_if_someone_is_logged_in?
        !set_current_user.nil?
    end

    def authorized_to_see_page
        redirect_to login_path unless check_and_see_if_someone_is_logged_in?
    end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

    before_action :get_appointment, only: [:show, :edit, :update, :destroy]


    def new
        @appointment = Appointment.new
        @therapists = Therapist.all
        @apptimes = Apptime.all
    end

    def create
        @appointment = @current_user.appointments.create(appointment_params)
        redirect_to appointments_path
    end

    def index
        @appointments = @current_user.appointments
    end

    def show
    end

    def edit
        @therapists = Therapist.all
        @apptimes = Apptime.all
    end

    def update
        @appointment.update(appointment_params)
        redirect_to appointments_path
    end

    def destroy
        @appointment.destroy
        redirect_to appointments_path
      end


    private

    def get_appointment
        @appointment = Appointment.find(params[:id])
    end

    def appointment_params
        appointment_params = params.require(:appointment).permit(:user_id, :therapist_id, :date, :apptime_id)
    end


end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
    def index
        @goals = @current_user.goals
    end

    def new
        @goal = Goal.new
    end

    def create
        goal_param = params.require(:goal).permit(:content)
        @goal = @current_user.goals.create(goal_param)
        redirect_to goals_path
    end

    def show
        @goal = Goal.find(params[:id])
    end

    def destroy
        @goal = Goal.find(params[:id])
        @goal.destroy
        redirect_to goals_path
    end

    def edit
        @goal = Goal.find(params[:id])
    end

    def update
        @goal = Goal.find(params[:id])
        goal_param = params.require(:goal).permit(:goal_status)
        @goal.update(goal_param)
        redirect_to goals_path
    end

end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
    def index
        @journals = @current_user.journals
    end

    def show
        @journal = Journal.find(params[:id])
    end

    def new
        @journal = Journal.new
    end

    def create
        @journal = @current_user.journals.create(journal_params)
        redirect_to journals_path
    end

    def destroy
        @journal = Journal.find(params[:id]) 
        @journal.destroy
        redirect_to journals_path
    end

    def edit
        @journal = Journal.find(params[:id])
    end

    def update
        @journal = Journal.find(params[:id])
        journal_params = params.require(:journal).permit(:content)
        @journal.update(journal_params)
        redirect_to journals_path
    end


    private

    def journal_params
        journal_params = params.require(:journal).permit(:date, :content)
    end

 


    
end

app/controllers/therapists_controller.rb
class TherapistsController < ApplicationController
    def show
        @therapist = Therapist.find(params[:id])
    end

    def index
        @therapists = Therapist.all
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authorized_to_see_page, only: [:login, :handle_login, :new, :create]

    def show
        @user = User.find(params[:id])
    end

    def login
      @error = flash[:error]
    end

    def handle_login
        @user = User.find_by(username: params[:username])
        if @user && @user.authenticate(params[:password])
          # If the student is found AND their password matches
          session[:user_id] = @user.id
          redirect_to profile_path
        else
          flash[:error] = "Incorrect username or password"
          redirect_to login_path
        end
      end

      def logout
        session[:student_id] = nil
        redirect_to login_path
      end

      def profile
        render :profile
      end

      def new
        @errors = flash[:errors]
        @user = User.new
      end

      def create
        user_params = params.require(:user).permit(:name, :username, :password)
        @user = User.create(user_params)

        if @user.valid?
          session[:user_id] = @user.id
          redirect_to login_path
        else
          flash[:errors] = @user.errors.full_messages
          redirect_to new_user_path
      end
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/therapists_helper.rb
module TherapistsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/edit.erb
<center> <div class="container">
<div class="card-transparent"
<div class="card border-0 shadow my-1">
  <div class="card-body p-1">
  <br></br>
    <h1 class="font-weight-light">Update Appointment</h1>
   


<%= form_for @appointment do |f| %>
  <strong>
  <%= f.label :date%>
  <%= f.date_select :date %> <br/><br/>
  <%= f.label :apptime_id, "Time"%>
  <%= f.collection_select :apptime_id, @apptimes, :id, :time %> <br/><br/>
  <%= f.label :therapist_id, "Therapist" %>
  <%= f.collection_select :therapist_id, @therapists, :id, :name %> <br/><br/>
  </strong>
  <%= f.submit "Update", class: 'btn btn-success' %>
<% end %>
</div>
    </div>
  </div>
</div>
</center>

app/views/appointments/index.erb
<center><% if @appointments == [] %>
    <br></br>
    <strong><p><%= "You have no appointments." %></p></strong>
<% end %>
</center>
<center><%= link_to "New Appointment", new_appointment_path, :class => "btn btn-primary btn-lg" %></center>
<br></br>

<center>
<div class="btn-group-vertical">

    <% @appointments.each do |appointment| %>
        <%= link_to appointment.date, appointment_path(appointment.id), :class => "btn btn-secondary btn-lg" %>
    <% end %>

</div>
</center>

app/views/appointments/new.erb
<center> <div class="container">
<div class="card-transparent"
<div class="card border-0 shadow my-1">
  <div class="card-body p-1">
    <h1 class="font-weight-light">New Appointment</h1>
   


<%= form_for @appointment do |f| %>
  <strong>
  <%= f.label :date%>
  <%= f.date_select :date %> <br/><br/>
  <%= f.label :apptime_id, "Time"%>
  <%= f.collection_select :apptime_id, @apptimes, :id, :time %> <br/><br/>
  <%= f.label :therapist_id, "Therapist" %>
  <%= f.collection_select :therapist_id, @therapists, :id, :name %> <br/><br/>
  </strong>
  <%= f.submit "Submit", class: 'btn btn-success' %>
<% end %>
</div>
    </div>
  </div>
</div>
</center>

app/views/appointments/show.erb
<br></br>
<center>
<div class="card bg-white mb-3">
    <div class="card-body">
        <p class="card-text">
        <%= "You have an appointment with #{@appointment.therapist.name} on #{@appointment.date} at #{@appointment.apptime.time}." %>
        </p>
        <p>
            <%= button_to "Update Appointment", {:controller => "appointments", :action => "edit", :user_id => session[:user_id]}, :method => :post, :class => "btn-primary btn-sm" %><br/><br/>
            <%= button_to "Cancel Appointment", @appointment, :method => :delete, :class => "btn-primary btn-sm" %>
        </p>
    </div>
</div>
</center>

app/views/goals/edit.erb
<center> <div class="container">
<div class="card-transparent"
<div class="card border-0 shadow my-1">
  <div class="card-body p-1">
  <br></br>
    <h1 class="font-weight-light">Update Status</h1>
   


<%= form_for @goal do |f| %>
  <strong>
  <%= f.label :goal_status, "Completed" %>
  <%= f.check_box :goal_status %> <br/><br/>
  </strong>
  <%= f.submit "Update", class: 'btn btn-success' %>
<% end %>
</div>
    </div>
  </div>
</div>
</center>

app/views/goals/index.erb
<br></br>
<center><h2> <%= link_to "New Goal", new_goal_path, :class => "btn btn-primary btn-lg" %></h2></center>

<br></br>

<center>
    <% @goals.each do |goal| %>
          <li>  <%= link_to "#{goal.content} | #{goal.status}", goal_path(goal), :class => "btn btn-secondary btn-md" %> <br></br>
          </li>
    <% end %>

</center>

app/views/goals/new.erb
  <center><div class="container">
<div class="card-transparent"
<div class="card border-0 shadow my-1">
  <div class="card-body p-1">
    <h1 class="font-weight-light">New Goal</h1>

<%= form_for @goal do |f| %>
  <strong>
  <%= f.label :content %>
  <%= f.text_area :content %> <br/>
  </strong>
  <%= f.submit "Let's do this!", class: 'btn btn-success' %>
<% end %>
</div>
   </div>
  </div>
</div>
</center>

app/views/goals/show.erb
<br></br>
<center>
<div class="card bg-white mb-3">
    <div class="card-body">
        <h5 class="card-title"><%= @goal.content %></h5>
        <p>
        <%= button_to "Update Status", edit_goal_path(@goal), :class => "btn-primary btn-sm" %><br/><br/>
        <%= button_to "Remove Goal", @goal, :method => :delete, :class => "btn-primary btn-sm" %>
        </p>
    </div>
</div>
</center>

app/views/journals/edit.erb
  <center> <div class="container">
<div class="card-transparent"
<div class="card border-0 shadow my-1">
  <div class="card-body p-1">
    <h1 class="font-weight-light">Edit Entry</h1>
   
<%= form_for @journal do |f| %>
  <strong>
  <%= f.label :content%>
  <%= f.text_area :content %> <br/><br/>
  <%= f.submit "Update", class: 'btn btn-success' %>
<% end %>
</div>
    </div>
  </div>
</div>
</center>

app/views/journals/index.erb
<br></br>
<center><h2> <%= link_to "New Journal Entry", new_journal_path, :class => "btn btn-primary btn-lg" %></center>

<br></br>

<div class="row">
    <% @journals.each do |journal| %>
        <section class="col-sm-6 col-md-4 col-lg-3">
            <div class="card mb-4" style="width: 16rem; height: 15rem">
                <div class="card-body">
                    <h5 class="card-title"><%= journal.date %></h5>
                    <p class="card-text "><%= journal.content[0...90] %>...</p>
                    <%= link_to "view more", journal_path(journal), :class => "btn btn-secondary btn-sm"%>
                </div>
            </div>
        </section>
    <% end %>
</div>

app/views/journals/new.erb
<center><div class="container">
<div class="card-transparent"
<div class="card border-0 shadow my-1">
  <div class="card-body p-1">
    <h1 class="font-weight-light">New Entry</h1>

<%= form_for @journal do |f| %>
  <strong>
  <%= f.label :date %>
  <%= f.date_select :date %> <br/>
  <%= f.label :content %>
  <%= f.text_area :content%><br/>
  </strong>
  <%= f.submit "Submit", class: 'btn btn-success' %>
<% end %>
</div>
   </div>
  </div>
</div>
</center>

app/views/journals/show.erb
<br></br>
<center>
<div class="card bg-white mb-3">
    <div class="card-body">
        <h5 class="card-title"><%= @journal.date %></h5>
        <p class="card-text">
        <%= @journal.content %>
        </p>
        <p>
        <%= button_to "Edit entry", {:controller => "journals", :action => "edit", :user_id => session[:user_id]}, :method => :post, :class => "btn-primary btn-sm"  %>
        <br></br>
        <%= button_to "Delete entry", @journal, :method => :delete, :class => "btn-primary btn-sm" %>
        </p>
    </div>
</div>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Mindful</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  
  </head>

  <body>
  <% if @current_user != nil %>
    <nav>
    <div class="btn-group">
      <%= button_to "MAIN MENU", profile_path, :class => "btn btn-secondary btn-sm" %> 
      </div>
      
      </nav>

      <nav class="navbar fixed-bottom navbar-dark bg-dark">
      <%= button_to "LOG OUT", logout_path, method: :delete, :class => "btn btn-secondary btn-sm" %>
  
</nav>
  <% end %>
  <center><h1 class="text-md-center text-lowercase display-3 mt-1">Mindfully</h1></center>
  <center><img src= "https://lh3.googleusercontent.com/5UQ7vU_4_SjfNjUJGwPiscNAeuFZcjThDau0xbct3Al1FtaG-feLFxlwU84QQCEoDIPe_an98tibuO28YfMNUMSnkR02wotL1NZfLKSjIHCNuKmC4n_8buGI-dnPzF1cLKGUiBEP1Q=w2400" width="100" height="50"></center>

  <%= yield %>

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>



</html>

app/views/therapists/index.erb
<br></br>
<div class="row">
    <% @therapists.each do |therapist| %>
        <section class="col-sm-6 col-md-4 col-lg-3">
            <div class="card mb-4" style="width: 16rem; height: 40rem">
                <img src=<%= therapist.image_url %> style="height: 20rem;" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title"><%= "#{therapist.name}, #{therapist.title}" %></h5>
                    <p class="card-subtitle sm"><em><%= therapist.specialty %></em></p>
                    <p class="card-text "><%= therapist.description[0...90] %>...</p>
                    <%= link_to "view more", therapist_path(therapist), :class => "btn btn-primary btn-sm"%>
                </div>
            </div>
        </section>
    <% end %>
</div>

app/views/therapists/show.erb
<div class="card bg-white mb-3">
    <div class="card-body">
        <h1 class="card-title"><%= @therapist.name %></h1>
        <strong><p class="card-subtitle"><%=@therapist.title %></em></p></strong>
        <img style="height: 30rem; width: 25rem;" class="card-img mx-auto d-block mb-3" alt="..." src=<%= @therapist.image_url %> >
        <strong><p class="card-description"><%= "Specialty: #{@therapist.specialty}" %></p></strong>
        <p class="card-text"><%= @therapist.description %>
        </p>
        <p>
            <center><%= link_to 'Make an Appointment', new_appointment_path, :class => "btn-primary btn-md" %></center>
        </p>
    </div>
</div>

app/views/users/login.erb
<div class="container">
<div class="card-transparent"
<div class="card border-0 shadow my-1">
  <div class="card-body p-1">
  <center>
    <h1 class="font-weight-light"></h1>
    
    <% if @error %>
    <p style= "color: red"> <%= @error %></p>
  <% end %>

<%= form_tag "/handle_login" do %>
    <strong>
    <div class="form-group"> 
        <%= label_tag :username %>
        <%= text_field_tag :username %>
    </div>
    <div class="form-group">
        <%= label_tag :password %>
        <%= password_field_tag :password %>
    </div></strong>
        <%= submit_tag "Login!", class: 'btn    btn-success' %>
        <% end %> 
        <%= button_to "No account? Register!", "/users/new" %>
    </div>
    </div>
</div>
</div>



<br></br>

app/views/users/new.erb
<div class="container">
<div class="card-transparent"
<div class="card border-0 shadow my-1">
  <div class="card-body p-1">
  <center>
    <h1 class="font-weight-light">Register</h1>
    <br></br>
      <% if @errors %>
        <% @errors.each do |error|%>
        <p style= "color: red"> <%= error %></p>
        <% end %>
      <% end %>

<%= form_for @user do |f| %>
  <strong>
  <%= f.label :name %>
  <%= f.text_field :name %> <br/>
  <%= f.label :username %>
  <%= f.text_field :username %><br/>
  <%= f.label :password %>
  <%= f.password_field :password %><br/>
  </strong>
  <%= f.submit "Ready!", class: 'btn btn-success' %>
<% end %>
</div>
    </div>
  </div>
</div>

app/views/users/profile.erb
<br></br>

<center><div class="btn-group-vertical">
<%= link_to "Appointments", appointments_path, :class => "btn btn-secondary btn-lg" %>
<%= link_to "Therapists", therapists_path, :class => "btn btn-secondary btn-lg" %>
<%= link_to "Goals", goals_path, :class => "btn btn-secondary btn-lg" %>
<%= link_to "Journal", journals_path, :class => "btn btn-secondary btn-lg" %>

  
</div>
</center>

app/views/users/show.erb
<h1> <%= @user.name %></h1>

<h2> <%= link_to "Appointments", appointments_path %> </h2>
<h2> <%= link_to "Goals", goals_path %> </h2>
<h2> <%= link_to "Journal", journals_path %> </h2>